/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:20
 */


#include <stdio.h>
#include <inttypes.h>
#include <stdbool.h>
#include <Kiso_Basics.h>
#include <Kiso_Retcode.h>
#include "SensorEnvironment.h"
#include "stdbool.h"
#include "ConnectivityLEDLeds.h"
#include "SensorAccelerometer.h"
#include "cgwTypes.h"
#include "MitaExceptions.h"
#include "stdint.h"
#include "application.h"

#ifndef KISO_MODULE_ID
#define KISO_MODULE_ID 0xCAFE
#endif

int8_t threshold = 0;

Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	return exception;
}

Retcode_T HandleEvery50Millisecond1(void* userParameter1, uint32_t userParameter2)
{
	
	KISO_UNUSED(userParameter1);
	KISO_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	vec3d_16_t SensorAccelerometerModalityPreparation_1;
	exception = SensorAccelerometer_readXyz(&SensorAccelerometerModalityPreparation_1);
	if(exception != NO_EXCEPTION) return exception;
	
	int16_t x;
	x = SensorAccelerometerModalityPreparation_1.x;
	int16_t y;
	y = SensorAccelerometerModalityPreparation_1.y;
	int16_t z;
	z = SensorAccelerometerModalityPreparation_1.z;
	bool _newConnectivityLEDLeds_R_2 = x > threshold;
	exception = ConnectivityLEDLeds_R_Write(&_newConnectivityLEDLeds_R_2);
	if(exception != NO_EXCEPTION) return exception;
	bool _newConnectivityLEDLeds_G_4 = y > threshold;
	exception = ConnectivityLEDLeds_G_Write(&_newConnectivityLEDLeds_G_4);
	if(exception != NO_EXCEPTION) return exception;
	bool _newConnectivityLEDLeds_B_6 = z > threshold;
	exception = ConnectivityLEDLeds_B_Write(&_newConnectivityLEDLeds_B_6);
	if(exception != NO_EXCEPTION) return exception;


	return NO_EXCEPTION;
}

Retcode_T HandleEvery1Second1(void* userParameter1, uint32_t userParameter2)
{
	
	KISO_UNUSED(userParameter1);
	KISO_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	EnvironmentData_t sensorEnvironmentModalityPreparation_1;
	exception = SensorEnvironmentRead(&sensorEnvironmentModalityPreparation_1);
	if(exception != NO_EXCEPTION) return exception;
	
	uint32_t h;
	h = sensorEnvironmentModalityPreparation_1.humidity;
	int32_t t;
	t = sensorEnvironmentModalityPreparation_1.temperature;
	uint32_t p;
	p = sensorEnvironmentModalityPreparation_1.pressure;
	printf("{\n\t\t\"humidity\": %" PRIu32 ",\n\t\t\"temperature\": %" PRId32 ",\n\t\t\"pressure\": %" PRIu32 "\n\t}\n", h, t, p);


	return NO_EXCEPTION;
}


