/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:20
 */


#ifndef APPLICATION_H
#define APPLICATION_H

#include <Kiso_Retcode.h>
#include "applicationTypes.h"


Retcode_T initGlobalVariables_application();

#endif
