baseURL = "/"
relativeURLs = true
uglyURLs = true
languageCode = "en-us"
title = "Kiso Website"
theme = "learn"

[params]
themeVariant = "kiso"

[outputs]
home = [ "HTML", "RSS", "JSON"]
[[menu.shortcuts]]
name = "<i class='fas fa-book'></i>Reference manual"
url = "http://kiso.rempler.de:8080/"
weight = 9
[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/eclipse/kiso"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-rocketchat'></i> Mattermost"
url = "https://mattermost.eclipse.org/eclipse/channels/kiso"
weight = 11
