/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:19
 */


#include <BCDS_Retcode.h>
#include "stdbool.h"
#include "MitaExceptions.h"
#include "ConnectivityLEDLeds.h"

#include "../../../../../boards/CommonGateway/bsp/include/BSP_CommonGateway.h"

bool ConnectivityLEDLeds_R_enabled = false;
bool ConnectivityLEDLeds_G_enabled = false;
bool ConnectivityLEDLeds_B_enabled = false;

Retcode_T ConnectivityLEDLeds_Setup(void)
{
	Retcode_T exception = RETCODE_OK;
	
	exception = BSP_LED_Connect();
	
	return exception;
	
	return NO_EXCEPTION;
}

Retcode_T ConnectivityLEDLeds_Enable(void)
{
	Retcode_T exception = RETCODE_OK;
	
	exception = BSP_LED_Enable((uint32_t) COMMONGATEWAY_LED_ALL);
	
	return exception;
	
	return NO_EXCEPTION;
}

/**
 * Provides read access to the r signal.
 */
Retcode_T ConnectivityLEDLeds_R_Read(bool* result)
{
	*result = ConnectivityLEDLeds_R_enabled;
	
	return NO_EXCEPTION;
}

/**
 * Provides write access to the r signal.
 */
Retcode_T ConnectivityLEDLeds_R_Write(bool* value)
{
	enum CommonGateway_LED_Commands_E command;
	ConnectivityLEDLeds_R_enabled = *value;
	if(*value) {
		command = COMMONGATEWAY_LED_COMMAND_ON;
	}
	else {
		command = COMMONGATEWAY_LED_COMMAND_OFF;
	}
	return BSP_LED_Switch(COMMONGATEWAY_LED_RED_ID, command);
	
	return NO_EXCEPTION;
}


/**
 * Provides read access to the g signal.
 */
Retcode_T ConnectivityLEDLeds_G_Read(bool* result)
{
	*result = ConnectivityLEDLeds_G_enabled;
	
	return NO_EXCEPTION;
}

/**
 * Provides write access to the g signal.
 */
Retcode_T ConnectivityLEDLeds_G_Write(bool* value)
{
	enum CommonGateway_LED_Commands_E command;
	ConnectivityLEDLeds_G_enabled = *value;
	if(*value) {
		command = COMMONGATEWAY_LED_COMMAND_ON;
	}
	else {
		command = COMMONGATEWAY_LED_COMMAND_OFF;
	}
	return BSP_LED_Switch(COMMONGATEWAY_LED_GREEN_ID, command);
	
	return NO_EXCEPTION;
}


/**
 * Provides read access to the b signal.
 */
Retcode_T ConnectivityLEDLeds_B_Read(bool* result)
{
	*result = ConnectivityLEDLeds_B_enabled;
	
	return NO_EXCEPTION;
}

/**
 * Provides write access to the b signal.
 */
Retcode_T ConnectivityLEDLeds_B_Write(bool* value)
{
	enum CommonGateway_LED_Commands_E command;
	ConnectivityLEDLeds_B_enabled = *value;
	if(*value) {
		command = COMMONGATEWAY_LED_COMMAND_ON;
	}
	else {
		command = COMMONGATEWAY_LED_COMMAND_OFF;
	}
	return BSP_LED_Switch(COMMONGATEWAY_LED_BLUE_ID, command);
	
	return NO_EXCEPTION;
}



