/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:19
 */


#ifndef MITA_EVENTS_H
#define MITA_EVENTS_H

#include <Kiso_Basics.h>
#include <Kiso_Retcode.h>
#include <Kiso_CmdProcessor.h>


extern CmdProcessor_T Mita_EventQueue;

Retcode_T HandleEvery50Millisecond1(void* userParameter1, uint32_t userParameter2);

Retcode_T HandleEvery1Second1(void* userParameter1, uint32_t userParameter2);


#endif
