/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:19
 */


#ifndef MITA_TIME_H
#define MITA_TIME_H

#include <BCDS_Retcode.h>


Retcode_T SetupTime(void);

Retcode_T EnableTime(void);

Retcode_T EveryHandleEvery50Millisecond1_Enable(void);
Retcode_T EveryHandleEvery1Second1_Enable(void);


#endif
