/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:19
 */


#include <FreeRTOS.h>
#include <Kiso_Basics.h>
#include <Kiso_CmdProcessor.h>
#include <timers.h>
#include <Kiso_Retcode.h>
#include "MitaTime.h"
#include "MitaExceptions.h"
#include "MitaEvents.h"

static TimerHandle_t timerHandleEvery50Millisecond1;
static TimerHandle_t timerHandleEvery1Second1;

static void InternalHandleEvery50Millisecond1(TimerHandle_t xTimer)
{
	KISO_UNUSED(xTimer);
	CmdProcessor_Enqueue(&Mita_EventQueue, HandleEvery50Millisecond1, NULL, 0);
}

static void InternalHandleEvery1Second1(TimerHandle_t xTimer)
{
	KISO_UNUSED(xTimer);
	CmdProcessor_Enqueue(&Mita_EventQueue, HandleEvery1Second1, NULL, 0);
}


Retcode_T SetupTime(void)
{
	timerHandleEvery50Millisecond1 = xTimerCreate("timerHandleEvery50Millisecond1", UINT32_C(50), pdTRUE, NULL, InternalHandleEvery50Millisecond1);
	
	timerHandleEvery1Second1 = xTimerCreate("timerHandleEvery1Second1", UINT32_C(1000), pdTRUE, NULL, InternalHandleEvery1Second1);
	
	if(timerHandleEvery50Millisecond1 == NULL || timerHandleEvery1Second1 == NULL)
	{
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES);
	}
	
	return NO_EXCEPTION;
}

Retcode_T EnableTime(void)
{
	Retcode_T result = NO_EXCEPTION;

	
	result = EveryHandleEvery50Millisecond1_Enable();
	if(result != NO_EXCEPTION)
	{
		return result;
	}
	
	result = EveryHandleEvery1Second1_Enable();
	if(result != NO_EXCEPTION)
	{
		return result;
	}
	
	return NO_EXCEPTION;
}

Retcode_T EveryHandleEvery50Millisecond1_Enable(void)
{
	xTimerStart(timerHandleEvery50Millisecond1, 0);
	
	return NO_EXCEPTION;
}

Retcode_T EveryHandleEvery1Second1_Enable(void)
{
	xTimerStart(timerHandleEvery1Second1, 0);
	
	return NO_EXCEPTION;
}


