/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:20
 */


#include <Kiso_Retcode.h>
#include "Kiso_I2CTransceiver.h"
#include "Kiso_MCU_I2C.h"
#include "Kiso_BSP_BME280.h"
#include "Kiso_BSP_BMA280.h"
#include "MitaExceptions.h"
#include "PlatformCGW.h"

static void I2CCallback(I2C_T i2c, struct MCU_I2C_Event_S event) {
	I2CTransceiver_LoopCallback(&i2cTransceiverStruct,  event);
}

Retcode_T PlatformCGW_Setup(void)
{
	Retcode_T exception = NO_EXCEPTION;
	i2cHandle = BSP_BME280_GetHandle(0);
	if(i2cHandle == NULL) {
		i2cHandle = BSP_BMA280_GetHandle(0);
	}
	if(i2cHandle == NULL) {
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_NULL_POINTER);
	}
	exception = I2CTransceiver_Init(&i2cTransceiverStruct, i2cHandle);
	if(exception != NO_EXCEPTION) return exception;
	exception = MCU_I2C_Initialize(i2cHandle, I2CCallback);
	if(exception != NO_EXCEPTION) return exception;
	return exception;
	
	return NO_EXCEPTION;
}

Retcode_T PlatformCGW_Enable(void)
{
	
	return NO_EXCEPTION;
}


