/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:20
 */


#ifndef PLATFORMCGW_CGW_13_H
#define PLATFORMCGW_CGW_13_H

#include <Kiso_Retcode.h>
#include "Kiso_I2CTransceiver.h"
#include "Kiso_MCU_I2C.h"


/**
 * Sets up the CGW_13.
 */
Retcode_T PlatformCGW_Setup(void);

/**
 * Enables the CGW_13 sensor.
 */
Retcode_T PlatformCGW_Enable(void);


I2cTranceiverHandle_T i2cTransceiverStruct;
I2C_T i2cHandle;

#endif
