/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:20
 */


#include <Kiso_Retcode.h>
#include "cgwTypes.h"
#include "PlatformCGW.h"
#include "Kiso_BSP_Board.h"
#include "bme280_defs.h"
#include "bme280.h"
#include "Kiso_BSP_BME280.h"
#include "MitaExceptions.h"
#include "SensorEnvironment.h"

#include "../../../../../boards/CommonGateway/bsp/include/BSP_CommonGateway.h"

int8_t bme280_Write(uint8_t address, uint8_t reg, uint8_t * data, uint16_t len)
{
    Retcode_T retcode = I2CTransceiver_Write(&i2cTransceiverStruct, address, reg, data, len);
    if (RETCODE_OK == retcode)
    {
        return BME280_OK;
    }
    else
    {
        return BME280_E_COMM_FAIL;
    }
}

int8_t bme280_Read(uint8_t address, uint8_t reg, uint8_t * data, uint16_t len)
{
    Retcode_T retcode = I2CTransceiver_Read(&i2cTransceiverStruct, address, reg, data, len);
    if (RETCODE_OK == retcode)
    {
        return BME280_OK;
    }
    else
    {
        return BME280_E_COMM_FAIL;
    }
}
struct bme280_dev bme280Struct = {
	.read = bme280_Read,
	.write = bme280_Write,
	.delay_ms = BSP_Board_Delay,
	.intf = BME280_I2C_INTF,
	.dev_id = COMMONGATEWAY_BME280_I2CADDRESS,
	.settings = {
	},
};
Retcode_T SensorEnvironmentRead(EnvironmentData_t* data) {
	struct bme280_data result;
	if(0 != bme280_get_sensor_data(BME280_ALL, &result, &bme280Struct)) {
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_FAILURE);
	}
	data->humidity = result.humidity;
	data->pressure = result.pressure;
	data->temperature = result.temperature;
	return RETCODE_OK;
}

Retcode_T SensorEnvironment_Setup(void)
{
	Retcode_T exception = NO_EXCEPTION;
	exception = BSP_BME280_Connect(COMMONGATEWAY_BME280_ID);
	if(exception != NO_EXCEPTION) return exception;
	return exception;
	
	return NO_EXCEPTION;
}

Retcode_T SensorEnvironment_Enable(void)
{
	Retcode_T exception = NO_EXCEPTION;
	exception = BSP_BME280_Enable(COMMONGATEWAY_BME280_ID);
	if(exception != NO_EXCEPTION) return exception;
	if (BME280_OK != bme280_init(&bme280Struct))
	{
		exception = RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_FAILURE);
	}
	if(exception != NO_EXCEPTION) return exception;
	BSP_Board_Delay(100);
	return exception;
	
	return NO_EXCEPTION;
}


