/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:19
 */


#include <BCDS_Retcode.h>
#include "cgwTypes.h"
#include "PlatformCGW.h"
#include "BCDS_BSP_Board.h"
#include "bma2x2.h"
#include "BCDS_I2CTransceiver.h"
#include "BCDS_MCU_I2C.h"
#include "BCDS_BSP_BMA280.h"
#include "MitaExceptions.h"
#include "SensorAccelerometer.h"

#include "../../../../../boards/CommonGateway/bsp/include/BSP_CommonGateway.h"

s8 bma280_Write(u8 address, u8 reg, u8 * data, u8 len)
{
    Retcode_T retcode = I2CTransceiver_Write(&i2cTransceiverStruct, address, reg, data, len);
    if (RETCODE_OK == retcode)
    {
        return SUCCESS;
    }
    else
    {
        return ERROR;
    }
}

s8 bma280_Read(u8 address, u8 reg, u8 * data, u8 len)
{
    Retcode_T retcode = I2CTransceiver_Read(&i2cTransceiverStruct, address, reg, data, len);
    if (RETCODE_OK == retcode)
    {
        return SUCCESS;
    }
    else
    {
        return ERROR;
    }
}
struct bma2x2_t bma280Struct = {
        .bus_read = bma280_Read,
        .bus_write = bma280_Write,
        .delay_msec = BSP_Board_Delay,
        .dev_addr = COMMONGATEWAY_BMA280_I2CADDRESS,
};
Retcode_T SensorAccelerometer_readXyz(vec3d_16_t* data) {
	struct bma2x2_accel_data bmaData;
	if(0 != bma2x2_read_accel_xyz(&bmaData)) {
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_FAILURE);
	}
	data->x = bmaData.x;
	data->y = bmaData.y;
	data->z = bmaData.z;
	return RETCODE_OK;
}

Retcode_T SensorAccelerometer_Setup(void)
{
	Retcode_T exception = NO_EXCEPTION;
	exception = BSP_BMA280_Connect(COMMONGATEWAY_BMA280_ID);
	if(exception != NO_EXCEPTION) return exception;
	return exception;
	
	return NO_EXCEPTION;
}

Retcode_T SensorAccelerometer_Enable(void)
{
	Retcode_T exception = NO_EXCEPTION;
	exception = BSP_BMA280_Enable(COMMONGATEWAY_BMA280_ID);
	if(exception != NO_EXCEPTION) return exception;
	if (SUCCESS != bma2x2_init(&bma280Struct))
	{
		exception = RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_FAILURE);
	}
	if(exception != NO_EXCEPTION) return exception;
	if (SUCCESS != bma2x2_set_bw(BMA2x2_BW_500HZ))
	{
		exception = RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_FAILURE);
	}
	if(exception != NO_EXCEPTION) return exception;
	if (SUCCESS != bma2x2_set_range(BMA2x2_RANGE_2G))
	{
		exception = RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_FAILURE);
	}
	BSP_Board_Delay(100);
	if(exception != NO_EXCEPTION) return exception;
	return exception;
	
	return NO_EXCEPTION;
}


