/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:20
 */


#ifndef SENSORENVIRONMENT_ENVIRONMENT_12_H
#define SENSORENVIRONMENT_ENVIRONMENT_12_H

#include <Kiso_Retcode.h>


/**
 * Sets up the environment_12.
 */
Retcode_T SensorEnvironment_Setup(void);

/**
 * Enables the environment_12 sensor.
 */
Retcode_T SensorEnvironment_Enable(void);



#endif
