/**
 * Generated by Eclipse Mita 0.2.0.
 * @date 2019-04-24 17:25:19
 */


#ifndef SENSORACCELEROMETER_ACCELEROMETER_11_H
#define SENSORACCELEROMETER_ACCELEROMETER_11_H

#include <BCDS_Retcode.h>
#include "cgwTypes.h"


/**
 * Sets up the accelerometer_11.
 */
Retcode_T SensorAccelerometer_Setup(void);

/**
 * Enables the accelerometer_11 sensor.
 */
Retcode_T SensorAccelerometer_Enable(void);



Retcode_T SensorAccelerometer_readXyz(vec3d_16_t* data);

#endif
