/********************************************************************************
* Copyright (c) 2010-2019 Robert Bosch GmbH
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Public License 2.0 which is available at
* http://www.eclipse.org/legal/epl-2.0.
*
* SPDX-License-Identifier: EPL-2.0
*
* Contributors:
*    Robert Bosch GmbH - initial contribution
*
********************************************************************************/

/**
 * @file
 * @brief Defines needed NVM object references to access the internal and
 * user data sections.
 */

#ifndef BCDS_NVMCONFIG_H_
#define BCDS_NVMCONFIG_H_

/* Include headers generated by NVMGenerator */
#include "BCDS_NVMUserPageItems.h"

/** Global instance for NMV section that is placed in user data flash.
 *  Usually the application has to create an instance of this structure.
 *  It may then be used by other modules to access the user data section */
//lint -e{956} This variable will not be accessed from some other thread. So this warning has been suppressed.
extern struct NVM_S  NVMUser;


#endif /* BCDS_NVMCONFIG_H_ */

