/*----------------------------------------------------------------------------*/
/*
 * Copyright (C) Bosch Connected Devices and Solutions GmbH.
 * All Rights Reserved. Confidential.
 *
 * Distribution only to people who need to know this information in
 * order to do their job.(Need-to-know principle).
 * Distribution to persons outside the company, only if these persons
 * signed a non-disclosure agreement.
 * Electronic transmission, e.g. via electronic mail, must be made in
 * encrypted form.
 */
/*----------------------------------------------------------------------------*/

/**
 * @file
 * @brief Defines needed NVM object references to access the internal and
 * user data sections.
 */

#ifndef BCDS_NVMCONFIG_H_
#define BCDS_NVMCONFIG_H_

/* Include headers generated by NVMGenerator */
#include "BCDS_NVMUserPageItems.h"

/** Global instance for NMV section that is placed in user data flash.
 *  Usually the application has to create an instance of this structure.
 *  It may then be used by other modules to access the user data section */
//lint -e{956} This variable will not be accessed from some other thread. So this warning has been suppressed.
extern struct NVM_S  NVMUser;


#endif /* BCDS_NVMCONFIG_H_ */

