cmake_minimum_required(VERSION 3.6)

if(${ENABLE_ALL_FEATURES})
    set(CFG_KISO_FEATURE_UART "1" CACHE STRING "Enable Kiso MCU-UART module")
    set(CFG_KISO_FEATURE_I2C "1" CACHE STRING "Enable Kiso MCU-I2C module")
    set(CFG_KISO_FEATURE_SPI "1" CACHE STRING "Enable Kiso MCU-SPI module")
    set(CFG_KISO_FEATURE_FLASH "1" CACHE STRING "Enable Kiso MCU-Flash module")
    # TODO: Enable watchdog feature once unit-tests are compilable
    set(CFG_KISO_FEATURE_WATCHDOG "0" CACHE STRING "Enable Kiso MCU-Watchdog module")
    set(CFG_KISO_FEATURE_PWM "1" CACHE STRING "Enable Kiso MCU-PWM module")
    set(CFG_KISO_FEATURE_SLEEP "1" CACHE STRING "Enable Kiso MCU-Sleep module")
    set(CFG_KISO_FEATURE_RNG "1" CACHE STRING "Enable Kiso MCU-RNG module")
    set(CFG_KISO_FEATURE_MCU_CRC "1" CACHE STRING "Enable Kiso MCU-CRC module")

    set(CFG_KISO_FEATURE_BSP_LED "1" CACHE STRING "Enable Kiso BSP-LED module")
    set(CFG_KISO_FEATURE_BSP_BUTTON "1" CACHE STRING "Enable Kiso BSP-Button module")
    set(CFG_KISO_FEATURE_BSP_CELLULAR_SARAR4N4 "1" CACHE STRING "Enable Kiso BSP-SARA-R4-N4 module")
    set(CFG_KISO_FEATURE_BSP_GNSS_MAXM8 "1" CACHE STRING "Enable Kiso BSP-GNSS-MAX-M8 module")
    set(CFG_KISO_FEATURE_BSP_BMA280 "1" CACHE STRING "Enable Kiso BSP-BMA280 module")
    set(CFG_KISO_FEATURE_BSP_BME280 "1" CACHE STRING "Enable Kiso BSP-BME280 module")
    set(CFG_KISO_FEATURE_BSP_BLE_CC2640 "1" CACHE STRING "Enable Kiso BSP-BLE-CC2640 module")
    set(CFG_KISO_FEATURE_BSP_MEMORY_W25 "1" CACHE STRING "Enable Kiso BSP-Memory-W25 module")
    set(CFG_KISO_FEATURE_BSP_TEST_INTERFACE "1" CACHE STRING "Enable Kiso BSP-Test-Interface module")
else()
    set(CFG_KISO_FEATURE_UART "1" CACHE STRING "Enable Kiso MCU-UART module")
    set(CFG_KISO_FEATURE_I2C "1" CACHE STRING "Enable Kiso MCU-I2C module")
    set(CFG_KISO_FEATURE_SPI "1" CACHE STRING "Enable Kiso MCU-SPI module")
    set(CFG_KISO_FEATURE_FLASH "0" CACHE STRING "Enable Kiso MCU-Flash module")
    set(CFG_KISO_FEATURE_WATCHDOG "0" CACHE STRING "Enable Kiso MCU-Watchdog module")
    set(CFG_KISO_FEATURE_PWM "0" CACHE STRING "Enable Kiso MCU-PWM module")
    set(CFG_KISO_FEATURE_SLEEP "0" CACHE STRING "Enable Kiso MCU-Sleep module")
    set(CFG_KISO_FEATURE_RNG "0" CACHE STRING "Enable Kiso MCU-RNG module")
    set(CFG_KISO_FEATURE_MCU_CRC "0" CACHE STRING "Enable Kiso MCU-CRC module")
    set(CFG_KISO_FEATURE_BSP_BMA280 "1" CACHE STRING "Enable Kiso BSP-BMA280 module")
    set(CFG_KISO_FEATURE_BSP_BME280 "1" CACHE STRING "Enable Kiso BSP-BME280 module")

    set(CFG_KISO_FEATURE_BSP_LED "1" CACHE STRING "Enable Kiso BSP-LED module")
    set(CFG_KISO_FEATURE_BSP_TEST_INTERFACE "1" CACHE STRING "Enable Kiso BSP-Test-Interface module")
endif()

configure_file(${KISO_CENTRAL_CONFIG_DIR}/Essentials/Kiso_HALConfig.h.in ${CURRENT_CONFIG_DIR}/Essentials/Kiso_HALConfig.h)
