cmake_minimum_required(VERSION 3.6)

if(${ENABLE_ALL_FEATURES})
    set(CFG_KISO_FEATURE_CMDLINEDEBUGGER "1" CACHE STRING "Enable Kiso Command Line Debugger module")
    set(CFG_KISO_FEATURE_CMDPROCESSOR "1" CACHE STRING "Enable Kiso Command Processor module")
    set(CFG_KISO_FEATURE_CRC "1" CACHE STRING "Enable Kiso CRC module")
    set(CFG_KISO_FEATURE_EVENTHUB "1" CACHE STRING "Enable Kiso Event Hub module")
    set(CFG_KISO_FEATURE_GUARDEDTASK "1" CACHE STRING "Enable Kiso Guarded Task module")
    set(CFG_KISO_FEATURE_ERRORLOGGER "1" CACHE STRING "Enable Kiso Error Logger module")
    set(CFG_KISO_FEATURE_LOGGING "1" CACHE STRING "Enable Kiso Logging module")
    set(CFG_KISO_FEATURE_QUEUE "1" CACHE STRING "Enable Kiso Queue module")
    set(CFG_KISO_FEATURE_RINGBUFFER "1" CACHE STRING "Enable Kiso Ring Buffer module")
    set(CFG_KISO_FEATURE_SLEEPCONTROL "1" CACHE STRING "Enable Kiso Sleep Control module")
    set(CFG_KISO_FEATURE_TASKMONITOR "1" CACHE STRING "Enable Kiso Task Monitor module")
    set(CFG_KISO_TASKMONITOR_MAX_TASKS "10" CACHE STRING "Number of Task Monitors to allocate")
    set(CFG_KISO_FEATURE_TLV "1" CACHE STRING "Enable Kiso TLV module")
    set(CFG_KISO_FEATURE_UARTTRANSCEIVER "1" CACHE STRING "Enable Kiso UART Transceiver module")
    set(CFG_KISO_FEATURE_I2CTRANSCEIVER "1" CACHE STRING "Enable Kiso I2C Transceiver module")
    set(CFG_KISO_FEATURE_XPROTOCOL "1" CACHE STRING "Enable Kiso XProtocol module")
    set(CFG_KISO_FEATURE_PIPEANDFILTER "1" CACHE STRING "Enable Kiso Pipe & Filter module")
else()
    set(CFG_KISO_FEATURE_CMDLINEDEBUGGER "1" CACHE STRING "Enable Kiso Command Line Debugger module")
    set(CFG_KISO_FEATURE_CMDPROCESSOR "1" CACHE STRING "Enable Kiso Command Processor module")
    set(CFG_KISO_FEATURE_CRC "1" CACHE STRING "Enable Kiso CRC module")
    set(CFG_KISO_FEATURE_EVENTHUB "1" CACHE STRING "Enable Kiso Event Hub module")
    set(CFG_KISO_FEATURE_GUARDEDTASK "1" CACHE STRING "Enable Kiso Guarded Task module")
    set(CFG_KISO_FEATURE_ERRORLOGGER "1" CACHE STRING "Enable Kiso Error Logger module")
    set(CFG_KISO_FEATURE_LOGGING "1" CACHE STRING "Enable Kiso Logging module")
    set(CFG_KISO_FEATURE_QUEUE "1" CACHE STRING "Enable Kiso Queue module")
    set(CFG_KISO_FEATURE_RINGBUFFER "1" CACHE STRING "Enable Kiso Ring Buffer module")
    set(CFG_KISO_FEATURE_SLEEPCONTROL "0" CACHE STRING "Enable Kiso Sleep Control module")
    set(CFG_KISO_FEATURE_TASKMONITOR "1" CACHE STRING "Enable Kiso Task Monitor module")
    set(CFG_KISO_TASKMONITOR_MAX_TASKS "10" CACHE STRING "Number of Task Monitors to allocate")
    set(CFG_KISO_FEATURE_TLV "1" CACHE STRING "Enable Kiso TLV module")
    set(CFG_KISO_FEATURE_UARTTRANSCEIVER "1" CACHE STRING "Enable Kiso UART Transceiver module")
    set(CFG_KISO_FEATURE_I2CTRANSCEIVER "1" CACHE STRING "Enable Kiso I2C Transceiver module")
    set(CFG_KISO_FEATURE_XPROTOCOL "1" CACHE STRING "Enable Kiso XProtocol module")
    set(CFG_KISO_FEATURE_PIPEANDFILTER "1" CACHE STRING "Enable Kiso Pipe & Filter module")
endif()

configure_file(${KISO_CENTRAL_CONFIG_DIR}/Utils/Kiso_UtilsConfig.h.in ${CURRENT_CONFIG_DIR}/Utils/Kiso_UtilsConfig.h)