#Root paths to library packages on which this package depends
ifeq ($(BCDS_MCU_FAMILY),stm32l4)
	BCDS_STM32CUBE_PATH ?= $(THIRD_PARTY_SHARED_PATH)/stm32cubel4
endif

ifeq ($(BCDS_MCU_FAMILY),stm32f7)
	BCDS_STM32CUBE_PATH ?= $(THIRD_PARTY_SHARED_PATH)/stm32cubef7
endif

#Paths to platform packages on which this package depends
BCDS_UTILS_PATH ?= $(BCDS_SHARED_PATH)/Utils

# Define the path for include directories.
BCDS_INCLUDES = \
	-I$(BCDS_PACKAGE_HOME)/include \
	-I$(BCDS_PACKAGE_HOME)/include/mcu \
	-I$(BCDS_PACKAGE_HOME)/include/mcu/stm32 \
	-I$(BCDS_PACKAGE_HOME)/include/bsp \
	-I$(BCDS_PACKAGE_HOME)/source \
	-I$(BCDS_PACKAGE_HOME)/source/mcu/stm32/$(BCDS_MCU_FAMILY) \
	-I$(BCDS_CONFIG_PATH) \
	-I$(BCDS_CONFIG_PATH)/Essentials \
	-I$(BCDS_CONFIG_PATH)/Utils \
	-I$(BCDS_STM32CUBE_PATH)/3rd-party/stm32cube/Drivers/$(BCDS_STM32_DEVICE_TYPE)_HAL_Driver/Inc \
	-I$(BCDS_STM32CUBE_PATH)/3rd-party/stm32cube/Drivers/$(BCDS_STM32_DEVICE_TYPE)_HAL_Driver/Inc/Legacy \
	-I$(BCDS_STM32CUBE_PATH)/3rd-party/stm32cube/Drivers/CMSIS/Include \
	-I$(BCDS_STM32CUBE_PATH)/3rd-party/stm32cube/Drivers/CMSIS/Device/ST/$(BCDS_STM32_DEVICE_TYPE)/Include \
	-I$(BCDS_STM32CUBE_PATH)/include


# Source and object files
BCDS_SOURCE_FILES = \
	$(wildcard source/*.c) \
	$(wildcard source/mcu/stm32/$(BCDS_MCU_FAMILY)/*.c)

DOXYGEN_PREDEFS += \
	__FILE__\
	__LINE__ \
	BCDS_EXCLUDE_FROM_DOC\
	BCDS_FEATURE_MCU_CRC=1 \
	BCDS_FEATURE_DMA=1 \
	BCDS_FEATURE_FLASH=1 \
	BCDS_FEATURE_FLASH_INTERN=1\
	BCDS_FEATURE_GPIO=1 \
	BCDS_FEATURE_I2C=1 \
	BCDS_FEATURE_LEUART=1 \
	BCDS_FEATURE_RNG=1 \
	BCDS_FEATURE_SLEEP=1 \
	BCDS_FEATURE_SPI=1 \
	BCDS_FEATURE_TIMER=1 \
	BCDS_FEATURE_WATCHDOG=1 \
	BCDS_FEATURE_UART=1 \
	BCDS_FEATURE_BSP_ACCEL_ADXL362=1 \
	BCDS_FEATURE_BSP_ACCEL_H3LIS=1 \
	BCDS_FEATURE_BSP_ADXL372=1 \
	BCDS_FEATURE_BSP_BMM150=1 \
	BCDS_FEATURE_BSP_BT_EM9301=1 \
	BCDS_FEATURE_BSP_BUTTON=1 \
	BCDS_FEATURE_BSP_CAN_SN65HVD234=1 \
	BCDS_FEATURE_BSP_CHARGER_BQ2405X=1 \
	BCDS_FEATURE_BSP_CHARGER_BQ2407X=1 \
	BCDS_FEATURE_BSP_GNSS_G7020=1 \
	BCDS_FEATURE_BSP_GPS_NEO7N=1 \
	BCDS_FEATURE_BSP_GSM_SIM800H=1 \
	BCDS_FEATURE_BSP_IRSENSOR_NODE=1 \
	BCDS_FEATURE_BSP_LED_LM2755=1 \
	BCDS_FEATURE_BSP_LED=1 \
	BCDS_FEATURE_BSP_LORA_RN2XX3=1 \
	BCDS_FEATURE_BSP_LORA_SX1272=1 \
	BCDS_FEATURE_BSP_MAX31865=1 \
	BCDS_FEATURE_BSP_MAX44009=1 \
	BCDS_FEATURE_BSP_MEMORY_AT45DB=1 \
	BCDS_FEATURE_BSP_MEMORY_S25FL116K=1 \
	BCDS_FEATURE_BSP_MEMORY_W25Q256FV=1 \
	BCDS_FEATURE_BSP_MEMORY_W25X40CL=1 \
	BCDS_FEATURE_BSP_MIC_AKU340=1 \
	BCDS_FEATURE_BSP_MIC_MAX4466=1 \
	BCDS_FEATURE_BSP_PWM_BUZZER=1 \
	BCDS_FEATURE_BSP_PWM_LED=1 \
	BCDS_FEATURE_BSP_SD_CARD=1 \
	BCDS_FEATURE_BSP_SENSOR_NODE=1 \
	BCDS_FEATURE_BSP_TEST_INTERFACE=1 \
	BCDS_FEATURE_BSP_TMP112=1 \
	BCDS_FEATURE_BSP_TMP116=1 \
	BCDS_FEATURE_BSP_UMTS_LISAU2=1 \
	BCDS_FEATURE_BSP_UMTS_QUECTELUC20=1 \
	BCDS_FEATURE_BSP_WIFI_CC3100MOD=1