
#Root paths to library packages on which this package depends
BCDS_TI_SDK_PATH ?= $(BCDS_TOOLS_PATH)/TI_BLE_Stack/v3.1.1/simplelink_cc2640r2_sdk_1_50_00_58
BCDS_TI_XDC_PATH ?= $(BCDS_TOOLS_PATH)/TI_BLE_Stack/v3.1.1/xdctools_3_50_03_33_core

#Paths to platform packages on which this package depends
BCDS_UTILS_PATH ?= $(BCDS_SHARED_PATH)/Utils

# Define the path for include directories.
BCDS_INCLUDES = \
	-I$(BCDS_PACKAGE_HOME)/include \
	-I$(BCDS_PACKAGE_HOME)/include/mcu \
	-I$(BCDS_PACKAGE_HOME)/include/mcu/ti_cc26xx \
	-I$(BCDS_PACKAGE_HOME)/include/bsp \
	-I$(BCDS_PACKAGE_HOME)/source \
	-I$(BCDS_PACKAGE_HOME)/source/mcu/ti_cc26xx \
	-I$(BCDS_CONFIG_PATH) \
	-I$(BCDS_CONFIG_PATH)/Essentials \
	-I$(BCDS_CONFIG_PATH)/Utils \
	-I$(BCDS_UTILS_PATH)/include \
	-I$(BCDS_TI_SDK_PATH)/source/ti 

# Source and object files
BCDS_SOURCE_FILES = \
	$(wildcard source/mcu/ti_cc26xx/*.c) \
	$(wildcard source/*.c)

DOXYGEN_PREDEFS += \
	__FILE__\
	__LINE__ \
	BCDS_EXCLUDE_FROM_DOC \
	BCDS_FEATURE_MCU_CRC=1 \
	BCDS_FEATURE_DMA=1 \
	BCDS_FEATURE_FLASH=1 \
	BCDS_FEATURE_FLASH_INTERN=1\
	BCDS_FEATURE_GPIO=1 \
	BCDS_FEATURE_I2C=1 \
	BCDS_FEATURE_LEUART=1 \
	BCDS_FEATURE_RNG=1 \
	BCDS_FEATURE_SLEEP=1 \
	BCDS_FEATURE_SPI=1 \
	BCDS_FEATURE_TIMER=1 \
	BCDS_FEATURE_WATCHDOG=1 \
	BCDS_FEATURE_UART=1 \
	BCDS_FEATURE_BSP_ACCEL_ADXL362=1 \
	BCDS_FEATURE_BSP_ACCEL_H3LIS=1 \
	BCDS_FEATURE_BSP_ADXL372=1 \
	BCDS_FEATURE_BSP_BMM150=1 \
	BCDS_FEATURE_BSP_BT_EM9301=1 \
	BCDS_FEATURE_BSP_BUTTON=1 \
	BCDS_FEATURE_BSP_CAN_SN65HVD234=1 \
	BCDS_FEATURE_BSP_CHARGER_BQ2405X=1 \
	BCDS_FEATURE_BSP_CHARGER_BQ2407X=1 \
	BCDS_FEATURE_BSP_GNSS_G7020=1 \
	BCDS_FEATURE_BSP_GPS_NEO7N=1 \
	BCDS_FEATURE_BSP_GSM_SIM800H=1 \
	BCDS_FEATURE_BSP_IRSENSOR_NODE=1 \
	BCDS_FEATURE_BSP_LED_LM2755=1 \
	BCDS_FEATURE_BSP_LED=1 \
	BCDS_FEATURE_BSP_LORA_RN2XX3=1 \
	BCDS_FEATURE_BSP_LORA_SX1272=1 \
	BCDS_FEATURE_BSP_MAX31865=1 \
	BCDS_FEATURE_BSP_MAX44009=1 \
	BCDS_FEATURE_BSP_MEMORY_AT45DB=1 \
	BCDS_FEATURE_BSP_MEMORY_S25FL116K=1 \
	BCDS_FEATURE_BSP_MEMORY_W25Q256FV=1 \
	BCDS_FEATURE_BSP_MEMORY_W25X40CL=1 \
	BCDS_FEATURE_BSP_MIC_AKU340=1 \
	BCDS_FEATURE_BSP_MIC_MAX4466=1 \
	BCDS_FEATURE_BSP_PWM_BUZZER=1 \
	BCDS_FEATURE_BSP_PWM_LED=1 \
	BCDS_FEATURE_BSP_SD_CARD=1 \
	BCDS_FEATURE_BSP_SENSOR_NODE=1 \
	BCDS_FEATURE_BSP_TEST_INTERFACE=1 \
	BCDS_FEATURE_BSP_TMP112=1 \
	BCDS_FEATURE_BSP_TMP116=1 \
	BCDS_FEATURE_BSP_UMTS_LISAU2=1 \
	BCDS_FEATURE_BSP_UMTS_QUECTELUC20=1 \
	BCDS_FEATURE_BSP_WIFI_CC3100MOD=1